env: "local" # local, dev, prod
# TODO Decompose database_url
# database_url: "host=localhost port=5432 user=app password=p@ssw0rd dbname=remedi_dev sslmode=disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
postgres:
  db_name: "remedi_dev"
  db_test_name: "remedi_test"
  host: "localhost"
  port: "5432"
  user: "app"
  password: "p@ssw0rd"
  sslmode: "disable"